name: 'HN summary page bot'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5,35 * * * *'

jobs:
  feed-processor:
    name: HN summary feed processor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm install
      - name: Build RSS
        run: node index.js
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist

